sudo: false
branches:
  only:
    - master
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
before_install:
  - pip install --upgrade pip
  - pip --version
install: python build.py dev
script: python build.py analyse
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#aspen"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
