language: python
python:
  - 2.5
  - 2.6
  - 2.7
install:
  - python setup.py -q install
  - pip install --use-mirrors simplejson
script: nosetests tests
notifications:
  email: false
  irc: "irc.freenode.org#aspen"
branches:
  only:
    - master 
